### ISSUE TITLE
Chrome Update issue

### ISSUE THREAD

**Issue by jpfteixeira** [HabitRPG/habitrpg-chrome#103]
Hi, 

since I upgraded to chrome 35.0.1916.114 the notifications on the extension have just dissapeared. Apparently, this is happening to several other notification extensions( My strict workflow extension went silent too).

I hope you can fix this. It was really helping a lot.

Cheers and best of luck,
Texmex

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg-chrome/commit/5622ba8307b99dcf7fb54c3a9ced192f4c7f9b20

@jpfteixeira @llamadonica thanks for the report, the code for notifications has been fixed and will go live with the next update which we hope to publish in a few weeks
