### ISSUE TITLE
Request: Google Tasks in Google Calendar should be integrated

### ISSUE THREAD

**Issue by Zweihander42** [HabitRPG/habitrpg-chrome#118]
The Google Task integration only works in the GMail interface however you can use tasks in Google Calendar. The tasks are the same but there are a few people (particularly those who don't use GMail in favour of a desktop client) who use tasks exclusively in the GCal interface.

**Comment by paglias** [comment]
@Zweihander42 thanks for the report. We're in the process of fixing the extension and this is definitively on my checklist :)

**Comment by paglias** [comment]
@Zweihander42 and it's done :) Could you check it's working? You may have to restart chrome/pc in order to get the updated extension. Let me know how it goes!

**Comment by paglias** [comment]
Mmm... it doesn't work if you open an event page without passing from the main view...

**Comment by Zweihander42** [comment]
Thanks! Just installed 2.3.2 - works well for checking off tasks in both cases (main view and standalone event page) but spotted one possible problem with task creation:

If you create a new task within the calendar (which you can do by clicking in the full day area at the top and selecting "Task" ), it seems to treat it the same as a task which you just unchecked: the "I thought it was done" message pops up with accompanying health docking. However, if you create a new task using the sidebar, that appears to work as intended so not a huge problem.

Full steps:
1. Open Google Calendar
2. Ensure that the "Tasks" calendar is open (including sidebar) and not hidden
3. Click somewhere in the full-day area
4. Select "Task" at the top of the popup
5. Create a task

Expected: New task created, nothing happens
Actual: New task created, "I thought it was done" message appears, health docked

Note: If the tasks calendar is hidden and you create a new task, the message doesn't popup and health doesn't appear to be docked.

This is the task creation area I'm referring to:
![image](https://cloud.githubusercontent.com/assets/1928813/5808615/6e213d3c-9ffd-11e4-9106-a9ca434d4582.png)

**Comment by Zweihander42** [comment]
Spotted one other thing:
If you change the date of the task, it will also bring up the "I thought it was done message".
On Calendar:
1. Open GCal
2. Create a new Task
3. Click and drag the task from one day to another

On Sidebar:
1. Open GCal, make sure sidebar is visible
2. Create a new Task
3. Click on the arrow next to the task
4. Change the Due Date of the task by clicking on the date and select another one on the calendar popup

Expected: Task moved, due date changed, nothing happens
Actual: Task moved, due date changed, "I thought it was done" message appears, health docked
