### ISSUE TITLE
Counter counts backwards and never uploads

### ISSUE THREAD

**Issue by omnisaurus** [HabitRPG/habitrpg-chrome#122]
Counter counts backwards and never uploads, I can't know if I'm actually getting any XP and if the extension is really working. Has someone worked around this?
It expires and then starts counting -0:01 and keeps decreasing. Goes to -0:02, then -0:03 and on and on.

**Comment by paglias** [comment]
@omnisaurus thanks for the report! I've just published an update that fixes this issue. It may take at least 60m before being published and you may have to restart chrome to get it. Let me know if it works correctly

**Comment by omnisaurus** [comment]
It works great now (:
Thanks!
