### ISSUE TITLE
Multi-level domains don't work

### ISSUE THREAD

**Issue by invernizzie** [HabitRPG/habitrpg-chrome#139]
I can't make the extension recognize `lanacion.com.ar` nor `www.lanacion.com.ar`. I've tried other similar cases such as `apps.sheenatimetracker.com` and it still won't work; however, `sheenatimetracker.com` works fine. I can't use `com.ar` of course, as it's a country TLD plus the .com domain and it'd apply to a great amount of sites.

If I offer a PR for the issue, is there a chance it would get merged?

**Comment by paglias** [comment]
@invernizzie I'll be happy to merge your PR as soon as you offer it!

**Comment by brazilianldsjaguar** [comment]
They're now supported with my latest PR.

**Comment by paglias** [comment]
The latest release on the Chrome WebStore includes the PR @brazilianldsjaguar so this should be fixed
