### ISSUE TITLE
Help needed: upgrade the extension to work with Habitica v3

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitrpg-chrome#144]
Hi,

we're nearing the release of version 3 of the Habitica API. 

One of the biggest changes is that every task will need a system-wide unique ID so it won't be possible anymore to use the same UID for every user (like `productivity`) but a unique value will have to be created for every user.

The new API docs can be found at http://v3.habitica.com/apidoc/.

If anyone from the community wants to make the necessary changes to upgrade the extension we'll be happy to help.

Thanks

**Comment by crookedneighbor** [comment]
[Here is a migration guide](http://devs.habitica.com/api-v2-v3-migration-guide/) for upgrading to version 3. If you have any questions, feel free to reach out on [Github](https://github.com/HabitRPG/habitrpg/issues) or the [Aspiring Comrades Guild](https://habitica.com/#/options/groups/guilds/2ff9822b-27f2-4774-98da-db349b57a38e).

**Comment by librarianmage** [comment]
Will this not work now, as API v2 has been removed?

**Comment by paglias** [comment]
This has been done, forgot to close the issue
